---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# leafdown

<!-- badges: start -->
<!-- badges: end -->

The goal of leafdown is to provide drill down functionality for leaflet choropleaths.

## Installation

You can install the released version of leafdown from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("leafdown")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("hoga-it/leafdown")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(leafdown)
library(raster)   
library(shiny)
library(leaflet)
```

Get spdfs
``` {r data_no_eval, eval = FALSE}
ger1 <- getData("GADM", country = "Germany", level = 1)
ger2 <- getData("GADM", country = "Germany", level = 2)
spdfs_list <- list(ger1, ger2)
```

```{r data_eval, echo=FALSE}
ger1 <- readRDS("inst/extdata/gadm36_DEU_1_sp.rds")
ger2 <- readRDS("inst/extdata/gadm36_DEU_2_sp.rds")
spdfs_list <- list(ger1, ger2)
```

TODO: Add further stuff


